simple red light classifier with opencv
ser94mor/self-driving-car-using-ros pull request #4
Opened 2019-01-17 22:17 UTC by pkorivi

Implemented simple red light classifier and interface to change the c…

2019-01-17 22:48 UTC, aoool commented
This pull request **introduces 3 alerts** when merging 0913b6edc55fab92c27814b346bfe6d86c99cabc into 8c3fdb3c728e35cff023e560a5c1039e26697909 - [view on LGTM.com](https://lgtm.com/projects/g/aoool/self-driving-car-using-ros/rev/pr-f8a3ef31d3b834d61fb1d304734dab2974c60a19)

**new alerts:**

* 2 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

2019-01-18 15:26 UTC, ser94mor requested changes
On my machine, it falsely classifies green lights as red, which leads to 2x time decrease in speed, though it does not lead to a complete stop. The car also does not stop on red lights. It decreases the speed down to 1 m/h and keeps moving with this low speed beyond the stop line when there is a red traffic light.

2019-01-18 15:26 UTC, ser94mor commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +        # rospy.loginfo("red :  %d",red_count)
Please, remove the commented debug code.

2019-01-18 15:26 UTC, ser94mor commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +import rospy
`rospy` package is not used here. Please, remove.

2019-01-18 15:26 UTC, ser94mor commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +                obj_x = int(rect_cordi[0][0])
The values assigned to local variables `obj_x` and `obj_y` are never used.

2019-01-18 15:26 UTC, ser94mor commented on ros/src/tl_detector/tl_detector.py
> +        cv_image = self.bridge.imgmsg_to_cv2(self.camera_image, "bgr8")
There is no such variable property. Replace with `self.camera_image_msg`.

2019-01-19 11:03 UTC, pkorivi commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +        # rospy.loginfo("red :  %d",red_count)
removed

2019-01-19 11:03 UTC, pkorivi commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +import rospy
removed

2019-01-19 11:06 UTC, pkorivi commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +                obj_x = int(rect_cordi[0][0])
The idea was to check where the lights are in the image but seemed kind of difficult to say, car pose may vary. In general, cases, it should be straight but as it was working without this implementation also I didn't use them. Removed this part of code

2019-01-19 11:07 UTC, pkorivi commented on ros/src/tl_detector/tl_detector.py
> +        cv_image = self.bridge.imgmsg_to_cv2(self.camera_image, "bgr8")
updated, copy paste issue :-( I was testing on my repository and looks like I pushed this by testing other repo.

2019-01-19 11:09 UTC, pkorivi commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +        # rospy.loginfo("red :  %d",red_count)
I also updated the false classification, it was due to detection of lights on the right side. I updated the thresholds. I didnt encounter the other situation where car doesnt stop on red lights in simulator. Try with this implementation once.

2019-01-19 15:22 UTC, ser94mor commented
Works with almost all traffic lights except for the last one on the Highway track. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2496083/51428650-1e519780-1c17-11e9-8f4e-235e1425aea5.gif)

2019-01-20 10:33 UTC, aoool commented on ros/src/waypoint_updater/waypoint_updater.py
>              # We subtract 2 below to stop front of the car in front of the stop line.
Please, update the comment to correspond to the current code state.

2019-01-20 10:34 UTC, ser94mor approved these changes

2019-01-20 11:22 UTC, Elgeweily approved these changes

2019-01-20 11:22 UTC, Elgeweily commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +                #Check for Square
Check for circle?

2019-01-20 11:22 UTC, Elgeweily commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +        im, contours, hierarchy = cv2.findContours(red_img,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
try to check for a minimum number of red pixels, instead of the shape of a red region

2019-01-20 11:28 UTC, pkorivi commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +                #Check for Square
It checks for both circle and length. 18<contourarea<900 checks for the number of pixels. This area of the polygon basically. and the len(approxcontours) checks for the type of contour. Though its not playing major role in our case as threshold is set low.

2019-01-20 12:43 UTC, merged