simple cnn classifier with model
ser94mor/self-driving-car-using-ros pull request #5
Opened 2019-01-20 14:24 UTC by Karthikeya108

I have not tested properly since I still have latency issues. It would be great if someone can test this. It worked for for the first traffic light.

2019-01-20 21:52 UTC, aoool commented
Problems:
- the car does not move after stopping on the first traffic light;
- CNN-classifier does not work with resolutions other than 640x480.

Video: https://carnd.slack.com/files/U3UUGFG0M/FFJKFM2CV/karthikclassifier.mp4

2019-01-20 22:04 UTC, ser94mor requested changes

2019-01-20 22:04 UTC, ser94mor commented on ros/src/CMakeLists.txt
> +../../../../../../../opt/ros/kinetic/share/catkin/cmake/toplevel.cmake
Don't change this. It should be:
```
aoool@dell:~/Workspace/self-driving-car-using-ros/ros/src$ ls -la CMakeLists.txt 
lrwxrwxrwx 1 aoool aoool 50 янв  8 01:45 CMakeLists.txt -> /opt/ros/kinetic/share/catkin/cmake/toplevel.cmake
```

2019-01-20 22:04 UTC, ser94mor commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +        json_file = open(path+'/light_classification/model/model.json', 'r')
Use `os.path.join(path, '/light_classification/model/model.json')` instead of `path+'/light_classification/model/model.json'`.

Use `with open(...) as json_file`, otherwise, in case of reading error, your file will not be automatically closed.

2019-01-20 22:04 UTC, ser94mor commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +        self.loaded_model.load_weights(path+"/light_classification/model/model.h5")
Use `os.path.join`

2019-01-20 22:04 UTC, aoool commented on ros/src/tl_detector/light_classification/tl_classifier.py
> -    def simple_opencv_red_color_classifier(self,image):
Do not remove OpenCV-based classifier. Inherit from TLClassifier and do the same for Pradeep's OpenCV-based classifier.

2019-01-20 22:04 UTC, aoool commented on ros/src/tl_detector/light_classification/tl_classifier.py
> +            print(light)
Either use rospy.log or remove.

2019-01-23 05:58 UTC, thejerrytan commented
@Karthikeya108 have u made any improvements to your classifier so i can hop on and review again?

2019-01-28 19:41 UTC, aoool commented
@Karthikeya108, I think we should merge it because it is a useful result that demonstrates different stages of our project. And it will be better to mention it in the README. I believe it won't take much time to integrate your model to a new code structure.

2019-02-02 17:38 UTC, closed without merging